import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  container: {
    padding: theme.spacing(8, 0, 6),
  },
  reviews: {
    margin: "160px",
  },
  reviews__show: {
    display: "flex",
  },
  reviews__title: {
    color: "white",
    fontWeight: "normal",
    fontSize: "32px",
    lineHeight: "40px",
  },
  reviews__line: {
    position: "absolute",
    width: "48px",
    height: "3px",
    left: "154px",
    marginTop: "4.2rem",
    background: "#0259EB",
    borderRadius: "16px",
  },
  reviews__view: {
    marginTop: "1.1rem",
    marginLeft: "700px",
    color: "#e5c558",
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "24px",
  },
  reviews__pagination: {
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "24px",
    /* identical to box height, or 150% */
    display: "flex",
    alignItems: "center",
    textAlign: "right",
    color: "#ffff",
    flex: "none",
    order: " 0",
    flexGrow: "0",
    margin: "0px 2px",
  },
  reviews__grid: {
    padding: "20px 0",
    marginTop: "30px",
  },
  reviews__card: {
    position: "absolute",
    marginTop: "45px",
    marginLeft: "10px",
    height: "235px",
    width: "305px",
    display: "flex",
    flexDirection: "column",
    background: "#0A0B1A",
    border: "2px solid #E5AF56",
    boxSizing: "border-box",
    borderRadius: "16px",
    zIndex: 10,
  },
  reviews__background: {
    marginTop: "40px",
    marginLeft: "10px",
    height: "235px",
    width: "290px",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    background: "linear-gradient(143.63deg, #276C73 5.43%, #5293E8 110.6%)",
    borderRadius: "16px",
  },

  reviews__heding: {
    display: "flex",
    marginTop: "10px",
    marginLeft: "20px",
  },
  reviews__profile: {
    marginTop: "15px",
    width: "40px",
    height: "40px",
    display: "flex",
    overflow: "hidden",
    position: "relative",
    fontSize: "1.25rem",
    alignItems: "center",
    flexShrink: "0",
    fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    lineHeight: "1",
    userSelect: "none",
    borderRadius: "50%",
    justifyContent: "center",
  },
  reviews__name: {
    position: "static",
    color: "#fff",
    fontFamily: "Quattrocento",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "16px",
    lineHeight: "32px",
  },
  reviews__address: {
    position: "static",
    color: "#E5C558",
    marginTop: "5px",
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "11px",
    lineHeight: "16px",
  },
  reviews__paraghraph:{
    position: "static",
    margin:'10px',
    fontFamily: 'Nunito',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#FFFFFF',
    opacity: '0.9',
  },
}));

export default useStyles;
